### ISSUE TITLE
Exception decoding type code with Aurora and a UNION ALL with DATE

### ISSUE THREAD

**Issue by richdrich** [elixir-ecto/myxql#124]
I get an exception running this query against `Aurora 5.7.mysql_aurora.2.07.2`: `SELECT CONVERT('2020-01-01', DATE) UNION ALL SELECT CONVERT('2020-01-02', DATE)`

It appears to return a field with type 14:  `NEWDATE` (which is documented not to happen).

This may be that this issue [Metadata from result sets for UNION ALL queries could say NEWDATE rather than DATE. (Bug #27422376)](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-22.html#mysqld-5-7-22-bug) isn't in the Aurora version of MySQL (I will raise this with AWS).

(I'm not sure if you should fix as I suspect it's more AWS's issue, but wanted to give a clue to anyone else who hits this).

```
iex(11)> query = "SELECT CONVERT('2020-01-01', DATE) UNION ALL SELECT CONVERT('2020-01-02', DATE)"
"SELECT CONVERT('2020-01-01', DATE) UNION ALL SELECT CONVERT('2020-01-02', DATE)"
iex(12)> { status, result } = Ecto.Adapters.SQL.query(Investapp.Repo, String.trim(query), [], log: false)

11:11:23.310 [error] GenServer #PID<0.456.0> terminating
** (DBConnection.ConnectionError) client #PID<0.414.0> stopped: ** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.type_code_to_atom/1
    (myxql 0.4.1) lib/myxql/protocol/values.ex:55: MyXQL.Protocol.Values.type_code_to_atom(14)
    (myxql 0.4.1) lib/myxql/protocol.ex:468: MyXQL.Protocol.decode_column_def/1
    (myxql 0.4.1) lib/myxql/protocol.ex:384: MyXQL.Protocol.decode_com_stmt_prepare_response/3
    (myxql 0.4.1) lib/myxql/client.ex:197: MyXQL.Client.recv_packets/6
    (myxql 0.4.1) lib/myxql/connection.ex:429: MyXQL.Connection.prepare/2
    (myxql 0.4.1) lib/myxql/connection.ex:80: MyXQL.Connection.handle_prepare/3
    (db_connection 2.2.2) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.2) lib/db_connection.ex:1240: DBConnection.prepare/4

    (db_connection 2.2.2) lib/db_connection/connection.ex:168: DBConnection.Connection.handle_cast/2
    (connection 1.0.4) lib/connection.ex:810: Connection.handle_async/3
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:259: :proc_lib.wake_up/3
Last message: {:"$gen_cast", {:stop, #Reference<0.2234016401.1160380417.138429>, %DBConnection.ConnectionError{message: "client #PID<0.414.0> stopped: ** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.type_code_to_atom/1\n    (myxql 0.4.1) lib/myxql/protocol/values.ex:55: MyXQL.Protocol.Values.type_code_to_atom(14)\n    (myxql 0.4.1) lib/myxql/protocol.ex:468: MyXQL.Protocol.decode_column_def/1\n    (myxql 0.4.1) lib/myxql/protocol.ex:384: MyXQL.Protocol.decode_com_stmt_prepare_response/3\n    (myxql 0.4.1) lib/myxql/client.ex:197: MyXQL.Client.recv_packets/6\n    (myxql 0.4.1) lib/myxql/connection.ex:429: MyXQL.Connection.prepare/2\n    (myxql 0.4.1) lib/myxql/connection.ex:80: MyXQL.Connection.handle_prepare/3\n    (db_connection 2.2.2) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4\n    (db_connection 2.2.2) lib/db_connection.ex:1240: DBConnection.prepare/4\n", severity: :error}, %MyXQL.Connection{client: %MyXQL.Client{connection_id: 76, sock: {:gen_tcp, #Port<0.42>}}, cursors: %{}, disconnect_on_error_codes: [:ER_MAX_PREPARED_STMT_COUNT_REACHED], last_ref: nil, ping_timeout: 15000, prepare: :named, queries: #Reference<0.2234016401.1160380418.144724>, transaction_status: :idle}}}
State: {MyXQL.Connection, %MyXQL.Connection{client: %MyXQL.Client{connection_id: 76, sock: {:gen_tcp, #Port<0.42>}}, cursors: %{}, disconnect_on_error_codes: [:ER_MAX_PREPARED_STMT_COUNT_REACHED], last_ref: nil, ping_timeout: 15000, prepare: :named, queries: #Reference<0.2234016401.1160380418.144724>, transaction_status: :idle}}
** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.type_code_to_atom/1

    The following arguments were given to MyXQL.Protocol.Values.type_code_to_atom/1:

        # 1
        14

    Attempted function clauses (showing 10 out of 26):

        def type_code_to_atom(1)
        def type_code_to_atom(2)
        def type_code_to_atom(3)
        def type_code_to_atom(4)
        def type_code_to_atom(5)
        def type_code_to_atom(6)
        def type_code_to_atom(7)
        def type_code_to_atom(8)
        def type_code_to_atom(9)
        def type_code_to_atom(10)
        ...
        (16 clauses not shown)

    (myxql 0.4.1) lib/myxql/protocol/values.ex:55: MyXQL.Protocol.Values.type_code_to_atom/1
    (myxql 0.4.1) lib/myxql/protocol.ex:468: MyXQL.Protocol.decode_column_def/1
    (myxql 0.4.1) lib/myxql/protocol.ex:384: MyXQL.Protocol.decode_com_stmt_prepare_response/3
    (myxql 0.4.1) lib/myxql/client.ex:197: MyXQL.Client.recv_packets/6
    (myxql 0.4.1) lib/myxql/connection.ex:429: MyXQL.Connection.prepare/2
    (myxql 0.4.1) lib/myxql/connection.ex:80: MyXQL.Connection.handle_prepare/3
    (db_connection 2.2.2) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.2) lib/db_connection.ex:1240: DBConnection.prepare/4
```

**Comment by wojtekmach** [comment]
Thank you for a detailed report and links.

The patch would be the following:

```diff
diff --git a/lib/myxql/protocol/values.ex b/lib/myxql/protocol/values.ex
index 9f2df37..4c74bec 100644
--- a/lib/myxql/protocol/values.ex
+++ b/lib/myxql/protocol/values.ex
@@ -36,6 +36,7 @@ defmodule MyXQL.Protocol.Values do
     mysql_type_time: 0x0B,
     mysql_type_datetime: 0x0C,
     mysql_type_year: 0x0D,
+    mysql_type_newdate: 0x0E,
     mysql_type_varchar: 0x0F,
     mysql_type_bit: 0x10,
     mysql_type_json: 0xF5,
@@ -71,6 +72,7 @@ defmodule MyXQL.Protocol.Values do
   defp column_def_to_type(column_def(type: :mysql_type_double)), do: :double
   defp column_def_to_type(column_def(type: :mysql_type_timestamp)), do: :datetime
   defp column_def_to_type(column_def(type: :mysql_type_date)), do: :date
+  defp column_def_to_type(column_def(type: :mysql_type_newdate)), do: :date
   defp column_def_to_type(column_def(type: :mysql_type_time)), do: :time
   defp column_def_to_type(column_def(type: :mysql_type_datetime)), do: :naive_datetime
   defp column_def_to_type(column_def(type: :mysql_type_newdecimal)), do: :decimal
```

but yeah, I agree that we probably shouldn't fix this. Given `NEWDATE` is an internal field so in theory, although it seems really unlikely, it could change in the future in which case we'd have even more cryptic error message.

I'm gonna leave this open for a while in case anyone runs into this. Thanks again!
