### ISSUE TITLE
No case clause matching

### ISSUE THREAD

**Issue by saleynik** [elixir-ecto/myxql#164]
Unfortunately I don't have any more details, but have been seeing this error in the logs:

```
** (CaseClauseError) no case clause matching: {:ok, %MyXQL.Result{columns: nil, connection_id: 6786606, last_insert_id: 0, num_rows: 0, rows: nil, num_warnings: 4}}
    (ecto_sql 3.7.2) lib/ecto/adapters/myxql.ex:265: Ecto.Adapters.MyXQL.insert/6
    (ecto 3.7.2) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.7.2) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto 3.7.2) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.7.2) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
```

**Comment by saleynik** [comment]
Sorry, this belongs to ecto_sql. Posted there: https://github.com/elixir-ecto/ecto_sql/issues/476
