### ISSUE TITLE
Storing a larger binary causes `FunctionClauseError`

### ISSUE THREAD

**Issue by k-cross** [elixir-ecto/myxql#51]
I have a table that stores a `mediumblob` in mysql 5.7.25 and it is blowing up when I try to store a larger `erlang_term` directly into the DB.

```
     ** (FunctionClauseError) no function clause matching in MyXQL.Protocol.Values.decode_string_lenenc/4

     The following arguments were given to MyXQL.Protocol.Values.decode_string_lenenc/4:

         # 1
         <<253, 71, 60, 1, 131, 116, 0, 0, 0, 5, 100, 0, 10, 95, 95, 115, 116, 114, 117, 99, 116, 95, 95, 100, 0, 24, 69, 108, 105, 120, 105, 114, 46, 83, 102, 83, 101, 114, 118, 105, 99, 101, 115, 46, 83, 99, 104, 101, 109, 97, ...>>

         # 2
         0

         # 3
         [:uint8, :binary]

         # 4
         ["I-9 (Sample Workflow)", "hg11ZxuZwBGiCV57", ~N[2019-04-04 17:20:25], ~N[2019-04-04 17:20:25], 761]

     Attempted function clauses (showing 4 out of 4):

         defp decode_string_lenenc(<<n::integer()-size(8), v::binary()-size(n), r::bitstring()>>, null_bitmap, t, acc) when n < 251
         defp decode_string_lenenc(<<252::integer(), n::integer()-little()-size(16), v::binary()-size(n), r::bitstring()>>, null_bitmap, t, acc)
         defp decode_string_lenenc(<<253::integer(), n::integer()-little()-size(32), v::binary()-size(n), r::bitstring()>>, null_bitmap, t, acc)
         defp decode_string_lenenc(<<254::integer(), n::integer()-little()-size(64), v::binary()-size(n), r::bitstring()>>, null_bitmap, t, acc)

     code: assert :ok == DraftServices.Seeder.seed_team(team_guid)
     stacktrace:
       (myxql) lib/myxql/protocol/values.ex:480: MyXQL.Protocol.Values.decode_string_lenenc/4
       (myxql) lib/myxql/protocol/messages.ex:400: MyXQL.Protocol.Messages.decode_resultset/4
       (myxql) lib/myxql/client.ex:167: MyXQL.Client.recv_packets/5
       (myxql) lib/myxql/connection.ex:95: MyXQL.Connection.handle_execute/4
       (ecto_sql) lib/ecto/adapters/sql/sandbox.ex:369: Ecto.Adapters.SQL.Sandbox.Connection.proxy/3
       (db_connection) lib/db_connection/holder.ex:277: DBConnection.Holder.holder_apply/4
       (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
       (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
       (db_connection) lib/db_connection.ex:540: DBConnection.parsed_prepare_execute/5
       (db_connection) lib/db_connection.ex:533: DBConnection.prepare_execute/4
       (myxql) lib/myxql.ex:199: MyXQL.query/4
       (ecto_sql) lib/ecto/adapters/sql.ex:571: Ecto.Adapters.SQL.execute!/4
       (ecto_sql) lib/ecto/adapters/sql.ex:538: Ecto.Adapters.SQL.execute/5
       (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```

I've been digging around to try and find some more context, but I'm not very strong on this topic. Please let me know if there's something that I can do to help, I'm not unwilling.

**Comment by josevalim** [comment]
Is it larger than 16mb? If so you are running into  #10.

**Comment by k-cross** [comment]
I will check the size. Looking around it seems like that function doesn't take a `mediumblob` or `FA`.

**Comment by k-cross** [comment]
Here's a `ls` of the file that's getting read and converted, `116K Mar 18 16:36 i9.json`

The json file itself is pretty small, I doubt the elixir struct is getting encoded to something larger than 1mb.

**Comment by wojtekmach** [comment]
@k-cross thank you for the report! v0.2.2 is released with the fix.

**Comment by k-cross** [comment]
Awesome! Thanks you @wojtekmach
