### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by MeerKatDev** [elixir-ecto/myxql#71]
I tried to migrate to myxql, so I changed the adapters and the dependencies. That's all I have to do according to the docs. Instead I cannot connect to the db (RDS on AWS, MySQL Aurora):

```
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 6038ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
        (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.execute/5
        (ecto) lib/ecto/repo/queryable.ex:153: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3
        (common) lib/models/user.ex:165: Common.Models.User.login/2
        (frontend) lib/frontend_web/controllers/page_controller.ex:127: FrontendWeb.PageController.create_session/2
        (frontend) lib/frontend_web/controllers/page_controller.ex:1: FrontendWeb.PageController.action/2
        (frontend) lib/frontend_web/controllers/page_controller.ex:1: FrontendWeb.PageController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (frontend) lib/frontend_web/endpoint.ex:1: FrontendWeb.Endpoint.plug_builder_call/2
        (frontend) lib/plug/debugger.ex:122: FrontendWeb.Endpoint."call (overridable 3)"/2
        (frontend) lib/frontend_web/endpoint.ex:1: FrontendWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:40: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /home/luca/Work/mmweb/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /home/luca/Work/mmweb/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /home/luca/Work/mmweb/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[error] MyXQL.Connection (#PID<0.420.0>) failed to connect: ** (DBConnection.ConnectionError) timeout
[error] MyXQL.Connection (#PID<0.419.0>) failed to connect: ** (DBConnection.ConnectionError) timeout
[error] MyXQL.Connection (#PID<0.419.0>) failed to connect: ** (DBConnection.ConnectionError) timeout
[error] MyXQL.Connection (#PID<0.420.0>) failed to connect: ** (DBConnection.ConnectionError) timeout
[error] MyXQL.Connection (#PID<0.419.0>) failed to connect: ** (DBConnection.ConnectionError) timeout
```

**Comment by wojtekmach** [comment]
I tested it against Aurora at some point so it is surprising you're running into timeouts. Maybe the repo is misconfigured? Could you paste your repo configuration (without username/password)?

Also please include the ecto_sql, myxql, and aurora version you're running.

**Comment by wojtekmach** [comment]
I just verified it against provisioned Aurora 5.6.10 and it works well.

Are you able to connect to your database using `mysql` CLI? If not, perhaps you need to allow inbound traffic from your machine in the security group settings? That would be one potential reason for timeouts.

**Comment by MeerKatDev** [comment]
Sorry, it was my machine. You can cancel this ticket.
