### ISSUE TITLE
FunctionClauseError on Lost Connection

### ISSUE THREAD

**Issue by maennchen** [elixir-ecto/myxql#89]
We sometime get those errors in our logs. I'm not sure what the cause of the errors is.

## Software Versions:

* `myxql`: `0.2.6`
* `elixir`: `1.8` (https://github.com/c0b/docker-elixir/blob/4122b4840bd762d1434424e1ec693929b0198c98/1.8/Dockerfile)
* MariaDB `maxscale`: `2.2.20`
* MariaDB Version:

```
mysql> SHOW VARIABLES LIKE "%version%";
+-----------------------------------+--------------------------------------------+
| Variable_name                     | Value                                      |
+-----------------------------------+--------------------------------------------+
| in_predicate_conversion_threshold | 1000                                       |
| innodb_version                    | 10.3.20                                    |
| protocol_version                  | 10                                         |
| slave_type_conversions            |                                            |
| system_versioning_alter_history   | ERROR                                      |
| system_versioning_asof            | DEFAULT                                    |
| version                           | 10.3.20-MariaDB-1:10.3.20+maria~bionic-log |
| version_comment                   | mariadb.org binary distribution            |
| version_compile_machine           | x86_64                                     |
| version_compile_os                | debian-linux-gnu                           |
| version_malloc_library            | system                                     |
| version_source_revision           | 352e7667877ec6603aff5234c003ef8c11885cd8   |
| version_ssl_library               | OpenSSL 1.1.1  11 Sep 2018                 |
| wsrep_patch_version               | wsrep_25.24                                |
+-----------------------------------+--------------------------------------------+
14 rows in set (0.03 sec)
```

## Error 

```
15:29:32.531 [error] GenServer #PID<0.28627.0> terminating
--
  | ** (FunctionClauseError) no function clause matching in anonymous fn/3 in MyXQL.Client.recv_packet/3
  | (myxql) lib/myxql/client.ex:146: anonymous fn(<<255, 211, 7, 35, 72, 89, 48, 48, 48, 76, 111, 115, 116, 32, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 116, 111, 32, 98, 97, 99, 107, 101, 110, 100, 32, 115, 101, 114, 118, 101, 114, 46>>, <<87, 0, 0, 0, 255, 135, 7, 35, 48, 56, 83, 48, 49, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 107, 105, 108, 108, 101, 100, 32, 98, 121, 32, 77, 97, 120, 83, 99, 97, 108, 101, 58, 32, 82, 111, 117, 116, 101, 114, ...>>, nil) in MyXQL.Client.recv_packet/3
  | (myxql) lib/myxql/client.ex:173: MyXQL.Client.recv_packets/5
  | (myxql) lib/myxql/connection.ex:122: MyXQL.Connection.ping/1
  | (db_connection) lib/db_connection/connection.ex:143: DBConnection.Connection.handle_cast/2
  | (connection) lib/connection.ex:810: Connection.handle_async/3
  | (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
  | (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
  | (stdlib) proc_lib.erl:259: :proc_lib.wake_up/3
  | Last message: {:"$gen_cast", {:ping, #Reference<0.244295645.171573249.154776>, %MyXQL.Connection{connection_id: 41471, cursors: %{}, disconnect_on_error_codes: [:ER_MAX_PREPARED_STMT_COUNT_REACHED], ping_timeout: 15000, prepare: :named, prpared_statements: %{}, sock: {:gen_tcp, #Port<0.24983>}, transaction_status: :idle}}}
```

**Comment by wojtekmach** [comment]
Thank you for the report,

> `<<255, 211, 7, 35, 72, 89, 48, 48, 48, 76, 111, 115, 116, 32, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 116, 111, 32, 98, 97, 99, 107, 101, 110, 100, 32, 115, 101, 114, 118, 101, 114, 46>>`

This translates to:

```elixir
MyXQL.Protocol.decode_generic_response(<<255, 211, 7, 35, 72, 89, 48, 48, 48, 76, 111, 115, 116, 32, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 32, 116, 111, 32, 98, 97, 99, 107, 101, 110, 100, 32, 115, 101, 114, 118, 101, 114, 46>>)                                                                                                                                                                                                        {:err_packet, 2003, "Lost connection to backend server."}
```

I'll make sure we're gracefully handling errors on ping.
